// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebSite.Models.WebSiteDB
{
    public partial class ForgotPassword
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public long IsReseted { get; set; }
        public string ExpiryDateTime { get; set; }

        public virtual User User { get; set; }
    }
}