// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace WebSite.Models.WebSiteDB
{
    public partial class Language
    {
        public string ID { get; set; }
        public long Seq { get; set; }
        public long IsEnabled { get; set; }
    }
}