// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace WebSite.Models.WebSiteDB
{
    public partial class WebsiteDBContext : DbContext
    {
        public WebsiteDBContext()
        {
        }

        public WebsiteDBContext(DbContextOptions<WebsiteDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ForgotPassword> ForgotPassword { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ForgotPassword>(entity =>
            {
                entity.Property(e => e.ExpiryDateTime).IsRequired();

                entity.Property(e => e.UserID).IsRequired();

                entity.HasOne(d => d.User)
                    .WithMany(p => p.ForgotPassword)
                    .HasForeignKey(d => d.UserID)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.Account).IsRequired();

                entity.Property(e => e.Birthday).IsRequired();

                entity.Property(e => e.Email).IsRequired();

                entity.Property(e => e.Name).IsRequired();

                entity.Property(e => e.Password).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}